### ISSUE TITLE
Bad backgroung crop

### ISSUE THREAD

**Issue by vladimirG123** [iacopomasi/face_specific_augm#11]
Bad backgroung crop in reconstructed frontal position. Exist empty areas with background around face, especcialy then face turned left or right. How modify background substraction to make it more accurate for transfrormed face? I cheked that facial points is accurate. Why this facial points don't use for accurate background substraction?

**Comment by iacopomasi** [comment]
Hi @vladimirG123,
if you just want to crop the faces more tightly, if the pose is computed correctly, all the faces after rendering are in the same coordinate system. So you can select beforehand a fixed bounding box, and crop the face accordingly using the same box every time.

I hope this helps.
