### ISSUE TITLE
additional pose models

### ISSUE THREAD

**Issue by kaishijeng** [iacopomasi/face_specific_augm#13]
How can I create new pose models below:

model3D_aug_+22_00_01.mat to  model3D_aug_+22_00_10.mat
and
model3D_aug_+44_00_01.mat to  model3D_aug_+44_00_10.mat

Thanks,

**Comment by iacopomasi** [comment]
Hi @kaishijeng ,
this is a good question and I see that it is requested by many users. We might release the script to generate those soon. Please see the reply to issue  #10 for more information.

Thanks.

**Comment by aovoc** [comment]
@kaishijeng Do you get the 22 degree and 40 degree 3D model? I meet the same problem. Hope for your help.

**Comment by twmht** [comment]
@iacopomasi 

Is it about to release?

**Comment by iacopomasi** [comment]
Hi @twmht,
yes, you can create as many pose models you want, look into [/render_mat_demo](https://github.com/iacopomasi/face_specific_augm/tree/master/render_mat_demo).

I hope this helps.
