### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by qmj123** [iacopomasi/face_specific_augm#14]
Hello，I want to ask you that there is a problem that "AttributeError: 'module' object has no attribute 'pairwise_distances_argmin_min'".Probably what is the reason?  Thank you！

**Comment by iacopomasi** [comment]
I am not sure but it sounds like you might not have the right version of the library that provides the function `'pairwise_distances_argmin_min`. Probably either you have an old library or too new. 
Check again `sklearn` version and see if you can call [this function](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances_argmin_min.html).
