### ISSUE TITLE
cv2 error in remap when running demo.py

### ISSUE THREAD

**Issue by kaishijeng** [iacopomasi/face_specific_augm#16]
I got the following error when run  python2 ./demo.py input/input_1.jpg

Number of faces detected: 1
> Yaw value mean:  1.06429849621
0 0
> Looking at file: input/input_1.jpg with model3D_aug_-00_00_01.mat
> Using pose model in model3D_aug_-00_00_01.mat
> Query image shape: (230, 230, 3)
OpenCV(3.4.0-dev) Error: Assertion failed (dst.cols < 0x7fff && dst.rows < 0x7fff && src.cols < 0x7fff && src.rows < 0x7fff) in remap, file /home/topspin/2TB/src/opencv/modules/imgproc/src/imgwarp.cpp, line 1749
Traceback (most recent call last):
  File "./demo.py", line 123, in <module>
    demo()
  File "./demo.py", line 98, in demo
    model3D.ref_U, eyemask, model3D.facemask, opts)
  File "/home/topspin/2TB/src/face_specific_augm/renderer.py", line 109, in render
    frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], prj_jnt, ind_jnt)
  File "/home/topspin/2TB/src/face_specific_augm/renderer.py", line 25, in warpImg
    np.squeeze( np.asarray( prj[1,:] ) ).astype('float32'),  cv2.INTER_CUBIC)
cv2.error: OpenCV(3.4.0-dev) /home/topspin/2TB/src/opencv/modules/imgproc/src/imgwarp.cpp:1749: error: (-215) dst.cols < 0x7fff && dst.rows < 0x7fff && src.cols < 0x7fff && src.rows < 0x7fff in function remap

**Comment by iacopomasi** [comment]
Very strange. It looks like you are using `OpenCV(3.4.0-dev)`. Can you try with a stable version of Opencv or Opencv 2.4.9?

Thanks.
