### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by pavibalaji** [iacopomasi/face_specific_augm#17]
Hi,

I am encountering the below error,
 File "/programs/Face-Pose-Net-master/face_renderer/ThreeD_Model.py", line 64, in createMask
    contours, hierarchy = cv2.findContours(eyemask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)
Can you help me fix this?

Thanks.

**Comment by iacopomasi** [comment]
Hi @pavibalaji ,
I think you are using OpenCV3. The code now does not support OpenCV3. 
Please, try to use Opencv2. See also #3  and #12.

I hope this helps.
