### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by sinyong01** [iacopomasi/face_specific_augm#20]
It was working fine for a minute or so... and then suddenly this error appears when I try to render a new image 

Number of faces detected: 1
('> Yaw value mean: ', 0.093203850386659223)
> Looking at file: input/input_1.jpg with model3D_aug_-75_00_01.mat
> Using pose model in model3D_aug_-75_00_01.mat
('> Query image shape:', (230L, 230L, 3L))
> skipping sym
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    demo()
  File "demo.py", line 98, in demo
    rendered_raw = myutil.cropFunc(pose,rendered_raw,crop_models[poseId])
IndexError: list index out of range

**Comment by iacopomasi** [comment]
Hi,
did you change some configuration in the config file? Last time I ran the default code was running fine, but maybe I didn't change all the code after I have imported the new rendered views.
