### ISSUE TITLE
Question about downloading the model

### ISSUE THREAD

**Issue by wanggongziZeo** [iacopomasi/face_specific_augm#21]
I can't download the model you provided,
and when I try to train my own caffemodel, the net accuracy only get 0.07, So what should I do to solve the problem?

**Comment by iacopomasi** [comment]
Hi @wanggongziZeo,
for the model I think you mean the face recognition network, right? 
Why you can't download the network? What is the problem?

For your problem, I think you should debug your training.

Best,

**Comment by wanggongziZeo** [comment]
I can't open the ulr "https://goo.gl/3vygej", and there's no response for downloading the  deep network "ResFace-101 a ResNet-101 network for face recognition"(Can't access this site)
Another question，I try VGG16 to train my own augmentation images(25 person, training images 34,836, test and validation are all 11612), but I only get about 0.86 accuracy, So how could I do to improve my acc, Thanks.

**Comment by iacopomasi** [comment]
Can you share with me your email address?
I will point to the model to download.

**Comment by wanggongziZeo** [comment]
Yeah, wanggongziZeo@163.com, Thanks
And, could you please send me your train.prototxt or deploy.prototxt file?
