### ISSUE TITLE
MATLAB 3D Model Renderer 

### ISSUE THREAD

**Issue by wanggongziZeo** [iacopomasi/face_specific_augm#22]
I try to obatain other pose model using your project "MATLAB 3D Model Renderer", but I find the OSG doesn't support .mat format model.
Now i have the 3d model(maybe from BFM), so how to use the model In your script, or in other words, how to convert the .mat file to the format that osg support?
Thanks

**Comment by aovoc** [comment]
@iacopomasi  I try to obtain other pose model, too. But  I can not download the renderer-pre-compiled-libs.tar.gz file. Can you upload it again, thanks very much!

**Comment by TalHassner** [comment]
@aovoc and all, I have recently migrated my personal webpage and some of the bigger files did not follow very well (too big for github). I am trying to solve these matters and hope to have the links working soon. Please check again in the next couple of weeks and let me know in case the links are still down.

**Comment by iacopomasi** [comment]
Hi all,
I am working to see if I can release the script that generates the views to be used with the renderer, but I am less sure that I can release the 3D models for reasons related to licensing. So you have to use as input your own 3D model for rendering.

I will let you know.
Best,

PS
@aovoc I can try to send you that file offline if you point me to your private email.

**Comment by aovoc** [comment]
@iacopomasi minqinch@gmail.com, thanks very much!  It will help me a lot.

**Comment by iacopomasi** [comment]
Sorry it took me a bit but finally: [Precomputing 3D views for Face Rendering](https://github.com/iacopomasi/face_specific_augm/tree/master/render_mat_demo) :+1:
