### ISSUE TITLE
Error when 'background=no' in the config.ini file

### ISSUE THREAD

**Issue by sbanerj1** [iacopomasi/face_specific_augm#27]
Hi Dr. Masi,

Thanks for sharing your code. It works perfectly fine on my 512x512 face images (with 'resizeCNN' = 512'), when 'background' is set as 'yes'. However, I get the following error when 'background' is set as 'no':

Number of faces detected: 1
> Yaw value mean:  8.28148317447
> Looking at file: FA10_04217d118.png with model3D_aug_-00_00_01.mat
> Using pose model in model3D_aug_-00_00_01.mat
> Query image shape: (512, 512, 3)
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    demo()
  File "demo.py", line 92, in demo
    model3D.ref_U, eyemask, model3D.facemask, opts)
  File "/afs/crc.nd.edu/user/s/sbanerj1/vol09/WACV++/MasiFG_Data/face_specific_augm/renderer.py", line 120, in render
    frontal_raw = warpImg(img, ref_U.shape[0], ref_U.shape[1], face_proj, facemask[:,0])
  File "/afs/crc.nd.edu/user/s/sbanerj1/vol09/WACV++/MasiFG_Data/face_specific_augm/renderer.py", line 26, in warpImg
    pixels = cv2.remap(img, np.squeeze(np.asarray(prj[0, :])).astype('float32').reshape(t_height, t_width), \
ValueError: cannot reshape array of size 17789 into shape (224,224)

Irrespective of the other parameters, I always get this same error when 'background = no'. Have you experienced this before?

Thanks,
Sandipan

**Comment by iacopomasi** [comment]
Hi @sbanerj1,
no, I never encountered this since I never used that much the option `render without background`. I cannot look into details now but probably there is some shape mismatch in this case: If you look at the error message, it seems that, in this case, the system cannot reshape the linearized array of size `17789` to the matrix `224x224`.

**Comment by sbanerj1** [comment]
Hi Dr. Masi,
I solved the problem by moving to OpenCV 3.1.0.5! To make the code compatible to OpenCV 3.3 I had changed the renderer.py file, as suggested by another user:

if prj.size != 0:
pixels = cv2.remap(img, np.squeeze( np.asarray( prj[0,:] ) ).astype('float32').reshape(t_height, t_width),\
np.squeeze( np.asarray( prj[1,:] ) ).astype('float32').reshape(t_height, t_width), cv2.INTER_CUBIC)
pixels = pixels.reshape(pixels.shape[0]*pixels.shape[1], pixels.shape[2])
# pixels = pixels[:,0,:]
new_img[idx,:] = pixels

However, that resulted in the shape mismatch when this block was accessed (when 'background = no'). Changing the OpenCV version and reverting to the original code works for both 'background' options.
