### ISSUE TITLE
Do we have synthetic lighting rendering in this repo?

### ISSUE THREAD

**Issue by nvinhphuc** [iacopomasi/face_specific_augm#28]
Do we have synthetic lighting rendering from "Dataset Augmentation for Pose and Lighting
Invariant Face Recognition" paper in this repo? If yes, can you point out how to use it? If no, do you any plan for implementing it?

**Comment by iacopomasi** [comment]
Hi @intheroom,
unfortunately, we do not deal with lighting variations and we are not planning to implement lighting.  This [repo](https://github.com/YadiraF/face3d) may help you out though.

I hope this helps,
