### ISSUE TITLE
question on "extreme poses and viewing conditions" and resnetON = yes

### ISSUE THREAD

**Issue by nyck33** [iacopomasi/face_specific_augm#32]
Hi, hope all is well.
If I set `resnetON = yes` in the config file, is that all I need to do to set the config to default to feed the rendered images to your Resnet 101?  
I noticed that when I set `resnetON = yes`, the rendered poses only range from 0 to about 40 and not full profile so where it says, ""This is a deep network trained to recognize faces appearing in extreme poses and viewing conditions" as description for Resnet 101, is this limited to about 0 to 40 and not full profile?  If so, do you think transfer learning on rendered pose 75 or even other full profile (pose 90) images work?
Also, what is in-plane alignment?

**Comment by iacopomasi** [comment]
Hi @nyck33,
Thanks for your interest. It has been a while now that I wrote this code. Yes, in theory, if you use that configuraiton the images produced are ready to be fed to the public model we have. I do not recall but we do not render all faces to all poses. If you do so you may get artifacts when rendering faces. The code does not provide in-plane alignment. You can see what is [here](https://talhassner.github.io/home/projects/DeepFaceSurvey/Masietal2018deepfacesurvey.pdf) in Fig. 2: it compensates for scale, rotation, and translation but only on the 2D image plane (the rotation is on the image plane, it cannot do 3D rotation).
