### ISSUE TITLE
adding more angles and directions

### ISSUE THREAD

**Issue by twmht** [iacopomasi/face_specific_augm#35]
Hi,

I have read https://github.com/iacopomasi/face_specific_augm/tree/master/render_mat_demo

to understand how to add more angles and directions to the face model.

it seems that each yaw angle should adjust the translation (https://github.com/iacopomasi/face_specific_augm/blob/master/render_mat_demo/adjust_translation.m), but how you determine these adjusted values?

by the way, how can I add roll and pitch?

**Comment by iacopomasi** [comment]
I was adjusting the translation manually to make use of the rendered model is in the center of the rendered image.

Yes, roll and pitch can be added should be easy but now I do not have time to do it

**Comment by twmht** [comment]
@iacopomasi 

I have sent you an email to request the 3D models you mentioned here (https://github.com/iacopomasi/face_specific_augm/tree/master/render_mat_demo), 
please take a look. 

thank you.

**Comment by iacopomasi** [comment]
I should have replied to the email.

**Comment by twmht** [comment]
@iacopomasi 

sorry to bother you.

I have sent you the replied email from basel. please take a look:)

btw, if possible, I can share the document or sample code for adding roll and pitch in this thread:).

**Comment by iacopomasi** [comment]
I have shared the model with you

**Comment by twmht** [comment]
@iacopomasi 

Big thanks for your share.

I tried to run the code with matlab2014b, but  segmentation fault.

it seems that my gcc version is too high. it may require gcc-4.7.x.

Can you share the ubuntu version you used for running the code?

is that ubuntu 13.04?

**Comment by iacopomasi** [comment]
I do not recall well it could have been Ubuntu from 2016 LTS
