### ISSUE TITLE
Rendering of other objects

### ISSUE THREAD

**Issue by Supersak80** [iacopomasi/face_specific_augm#4]
Is this code extensible to the rendering of other objects (such as vehicles), assuming that the face landmark detection step can be modified?

**Comment by TalHassner** [comment]
@Supersak80: Not easily, but yes. 

The code uses pre-computer projections from 3D to the output coordinate system These projections were obtained from our earlier tool, available [here](http://www.openu.ac.il/home/hassner/projects/poses). You'll need to use it to compute the projections to your desired output view(s). 

You'll also need to replace the way landmarks are used. The link about should give you some idea of how to do just that.

**Comment by qiufan** [comment]
@TalHassner  hello, thanks for sharing such  good codes. I want to know the which kind of 3D model you use to generate the projections 3D model?

**Comment by TalHassner** [comment]
@qiufan the rendering tool is based on the [open scene graph](http://www.openscenegraph.org/) library and can read and render (get projections for) any 3D model file format it can.

**Comment by qiufan** [comment]
@TalHassner  Oh, thank you for the reply very much. I have checked the earlier tool. In the figure, I see some projection examples. I am curious about the name of 3D face model file you use. Is it the reference 3D model from the USF(DARPA Human-ID 3D Face Database) claimed on the website?

**Comment by TalHassner** [comment]
It was a long time since I prepared that figure, and I'm not sure what 3D model I actually used. But it shouldn't matter -- any face model you can import into our renderer can work equally well.

**Comment by qiufan** [comment]
@TalHassner  Thank you very much~ I will try first.
