### ISSUE TITLE
ThreeD_Model.py line 62 error

### ISSUE THREAD

**Issue by yja1** [iacopomasi/face_specific_augm#5]
when run demo.py test.jpg 
error:
face_specific_augm-master/ThreeD_Model.py", line 62, in createMask contours, hierarchy = cv2.findContours(eyemask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)ValueError: too many values to unpack
thx~

**Comment by xiaoyun4** [comment]
@yja1 I aslo have the error. Have you been solved it? what should I do?

**Comment by iacopomasi** [comment]
You are probably using OpenCV3. The quickest way would be reverting back to OpenCV2.x

**Comment by yonihei** [comment]
i think this might solve it while keeping your openCV3;
https://github.com/iacopomasi/face_specific_augm/issues/12
