### ISSUE TITLE
How did I run the example of input1?

### ISSUE THREAD

**Issue by zhixuanli** [iacopomasi/face_specific_augm#6]
Hi every one, I'm a student from China.
Here's the blog of the whole process from installing opencv to run the imput1 example
May be can help you a little

http://www.cnblogs.com/QingHuan/p/6753440.html

<img width="1280" alt="2017-04-24 10 30 06" src="https://cloud.githubusercontent.com/assets/26455344/25320367/04984344-28d9-11e7-98c5-734e860fdbc1.png">

**Comment by zhixuanli** [comment]
<img width="928" alt="2017-04-24 10 17 24" src="https://cloud.githubusercontent.com/assets/26455344/25320388/2e0c3f0a-28d9-11e7-993c-e6f7e53b7f0f.png">
<img width="928" alt="2017-04-24 10 19 11" src="https://cloud.githubusercontent.com/assets/26455344/25320389/2e0dd022-28d9-11e7-9791-6a486a81143c.png">
![input_2_rendered_aug_-00_09](https://cloud.githubusercontent.com/assets/26455344/25320395/3a14af9e-28d9-11e7-93d9-ac52f2ac69f7.jpg)
![input_2_rendered_aug_-00_10](https://cloud.githubusercontent.com/assets/26455344/25320396/3a1578fc-28d9-11e7-8aee-64925f9f3986.jpg)
![input_2_rendered_aug_-40_01](https://cloud.githubusercontent.com/assets/26455344/25320397/3a24ac50-28d9-11e7-8a86-77bcbeeb375a.jpg)
![input_2](https://cloud.githubusercontent.com/assets/26455344/25320398/3a256bf4-28d9-11e7-8e96-79c4bd3fa139.jpg)

**Comment by iacopomasi** [comment]
OK. Thank you so much! I have added it as a link into our wiki page.

https://github.com/iacopomasi/face_specific_augm/wiki

Thanks again,
