### ISSUE TITLE
Demo might be broken

### ISSUE THREAD

**Issue by 4F2E4A2E** [iacopomasi/face_specific_augm#9]
I just committed #8 and was wondering which output the cmd:
`python demo.py image.jpg`
should be, can you please explain? image.jpg is a simple image file containing a face. The script ran and nothing happens.

**Comment by iacopomasi** [comment]
The demo is currently working in the main branch. I saw your pull request in order to use python3 but I have not merged yet and moreover now we have some conflicts to resolve between branches. For now I will keep my current version coded for py27.

Thanks.
